zuul:
  routes:
    my-service:
      path: /pilae/**
      serviceId: PILAE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:Pi143*3ur3K4@localhost:5000}/eureka/
